name: Build Svelte

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    uses: actions/checkout@v2
    uses: actions/setup-node@v2
    with:
      node-version: '12'
    name: Install packages
    run: npm i 
    run: npm run build
    run: npm run deploy